### ISSUE TITLE
Empty userAgent detected as Desktop

### ISSUE THREAD

**Issue by andreldm** [51Degreesmobi/51Degrees-Java#11] opened 2019-04-29 14:28 UTC
Consider the following snippet:

```
    Provider provider = new Provider(StreamFactory.create("/path/to/dataset"));
    Match match = provider.match("");
    System.out.println(match.getValues(FiftyOneDegreesPropertyNames.DEVICE_TYPE));
    System.out.println(match.getValues(FiftyOneDegreesPropertyNames.BROWSER_NAME));
    System.out.println(match.getValues(FiftyOneDegreesPropertyNames.PLATFORM_NAME));
```

The output is `Desktop, Unknown, Unknown`, but I expected the device type to be "Unknown". I'm using the enterprise dataset version `3.2-20190408` and device-detection-core version `3.2.18.1` . If the [lite dataset](https://github.com/51Degrees/51Degrees.mobi-Lite-Binary/blob/master/51Degrees-LiteV3_2.dat.gz) is used instead the output is `null, Unknown, Unknown`.

**Comment by JoshGrew51D** [comment] 2019-04-29 15:32
Hi There

The "Unknown" match values are due to the fact that those properties are not available within the Lite data file. You can see properties available within each data file type [here](https://51degrees.com/resources/property-dictionary). 

Matching on an empty string is defaulting to our Desktop/Emulator profile which has a DeviceType of Desktop.

Any questions just let me know.

**Comment by andreldm** [comment] 2019-04-29 16:00
Ok, right, but is there any way to disable this profile? Even random/gibberish strings seem to enable it.

**Comment by JoshGrew51D** [comment] 2019-04-30 09:52
You can choose to ignore it by adding logic around our [Match Metrics](https://github.com/51Degrees/Java-Device-Detection/blob/master/device-detection-examples/src/main/java/fiftyone/device/example/illustration/MatchMetrics.java). 

Using `match.getMethod` will return a result of 'None' for most cases, like the ones mentioned.

If you send us over some examples, we can review and advise why it is returning those specific results.

**Comment by andreldm** [comment] 2019-04-30 13:20
This is the updated sample:
```
IndirectDataset dataset = StreamFactory.create("com.51degrees.dat.enterprise-3.2-20190408");
Provider provider = new Provider(dataset);

Match match = provider.match("foobar");

System.out.println(match.getMethod());
System.out.println(match.getValues(FiftyOneDegreesPropertyNames.DEVICE_TYPE));
System.out.println(match.getValues(FiftyOneDegreesPropertyNames.BROWSER_NAME));
System.out.println(match.getValues(FiftyOneDegreesPropertyNames.PLATFORM_NAME));
```

And its output:
```
EXACT
Desktop
Unknown
Unknown
```

Sorry but I don't follow how `match.getMethod` could be helpful here.

**Comment by JoshGrew51D** [comment] 2019-04-30 14:10
It can be used to filter on match results that we are not confident have been identified correctly.

When matching, regardless of what is supplied, the algorithm will attempt to find the closest match to that string using a few different methods. 

For common terms like "foobar" you may find that we do indeed have it stored as a User-Agent in the database due to its use in testing, etc. However, it is clear that it is not a device so it will be defaulted to our Desktop/Emulator profile.

If you could into more detail on how you are trying to use the API, I am happy to advise.

**Comment by andreldm** [comment] 2019-04-30 18:26
> It can be used to filter on match results that we are not confident have been identified correctly.

Is there any example?

> For common terms like "foobar" you may find that we do indeed have it stored as a User-Agent in the database due to its use in testing, etc. However, it is clear that it is not a device so it will be defaulted to our Desktop/Emulator profile.

The output is the same for random strings such as `"GsFZluf15b"` and `"f0DiH50wttzijQsvL7jb")`. Are they also stored in the database?

> If you could into more detail on how you are trying to use the API, I am happy to advise.

Our use case is very simple, the code is basically the same from the previous sample, but sometimes User Agents may be null, empty or random, in those cases we should not report Desktop as the platform.

**Comment by JoshGrew51D** [comment] 2019-05-02 11:01
Slight amendment to my note above about many cases returning 'None' for random User-Agents. The issue is that the algorithm will try its best to find a match based on the evidence you have supplied. This is done through looking at specific substrings within the UA: Device / Operating System / Browser / known crawlers. 

In one of your examples using our [User-Agent tester](https://51degrees.com/resources/user-agent-tester?useragent=f0DiH50wttzijQsvL7jb) you can see that the substring it has linked to is simply 'f'. The behavior of the API may seem incorrect but that is due to these examples not being User-Agents devices would necessarily use.

A workaround is to filter out these out using additional logic. This can be done easily using `match.getMethod()` for both null and empty strings as they will both return 'None'.

Can i ask in what instance you would expect to see null, empty or random User-Agents?

**Comment by JoshGrew51D** [comment] 2019-05-13 08:24
Closing this issue for the time being. If you have any other questions just get in touch and I will be happy to advise.

**Closed as completed by JoshGrew51D** 2019-05-13 08:24 UTC
