### ISSUE TITLE
Infinite loop in Signature#getPropertyValuesAsString()

### ISSUE THREAD

**Issue by zackb** [51Degreesmobi/51Degrees-Java#7] opened 2017-04-25 18:08 UTC
getValues().hasNext() is always true so the loop never ends and results in an OutOfMemoryError

https://github.com/51Degrees/Java-Device-Detection/blob/master/device-detection-core/src/main/java/fiftyone/mobile/detection/entities/Signature.java#L311

**Comment by Steve51D** [comment] 2017-04-27 07:23
Hi, thanks for the feedback and apologies for any trouble this caused. The issue is now fixed on github and will be part of the next release.
For details, see this commit: https://github.com/51Degrees/Java-Device-Detection/commit/c0979724e004bdcc68a38f748699590907df10a3

Regards,
Steve.

**Closed as completed by Steve51D** 2017-04-27 07:23 UTC

**Comment by zackb** [comment] 2017-04-27 17:29
No trouble at all! Thanks for the quick fix!
